import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Promo } from "#/services/advertising/widgets/promo";
import { HeaderBar } from "#/structures/gadgets/headerBar/ui/HeaderBar";
import { TopMenu } from "#/structures/gadgets/topMenu";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <header>
                <Promo />
                <HeaderBar />
                <TopMenu />
            </header>
            <div
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </div>
        </div>
    );
}